version: '3.8'

services:
  web:
    build: ./backend
    container_name: api_taller_moviles
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1